// Archivo de constantes de texto en español para el frontend
export const TEXTS = {
  // Navegación y títulos
  appTitle: 'UPG',
  welcomeMessage: 'Bienvenido a la comunidad oficial. Aquí encontrarás canales, eventos y salas de voz para echar unas partidillas. Mantén el respeto y disfruta.',
  enterChat: 'Entrar al Chat',
  createImpostor: 'Crear Impostor',
  whatIsUPG: '¿Qué es UPG?',
  activeServers: 'Servidores Activos',
  loadingServers: 'Cargando servidores...',
  noActiveServers: 'No hay servidores activos.',
  beTheFirst: '¡Sé el primero en crear uno!',
  join: 'Unirse',
  full: 'Lleno',
  host: 'Host',
  waiting: 'En espera',
  passwordRequired: 'Contraseña requerida',
  enterPassword: 'Ingresa la contraseña',

  // Chat
  sendMessage: 'Enviar mensaje',
  messagePlaceholder: 'Escribir mensaje',
  sending: 'Enviando...',
  errorSending: 'Error al enviar',
  mention: 'MENCIÓN',
  admin: 'ADMIN',
  bot: 'BOT',
  typing: 'escribiendo...',
  welcomeToChat: '¡Bienvenido al chat!',
  realChat: 'Este es el chat real.',
  deleteMessage: 'Eliminar mensaje',
  kickUser: 'Expulsar usuario',
  banUser: 'Banear usuario y su IP',
  silenceUser: 'Silenciar usuario',
  changeColor: 'Cambiar color de usuario',
  trollMode: 'Modo troll',
  confirmKick: '¿Estás seguro de que quieres expulsar a',
  confirmBan: '¿Estás seguro de que quieres banear a',
  confirmSilence: '¿Silenciar a',
  confirmTroll: '¿Activar modo troll para',
  enterColor: 'Nuevo color HEX para',
  invalidColor: 'Color inválido. Usa formato HEX (#RRGGBB)',
  willNotSend: 'No podrá enviar mensajes hasta que lo des-silencies.',
  blockedIP: 'Esta acción también bloqueará su IP.',

  // Impostor game
  impostor: 'Impostor',
  hardModeDescription: 'El impostor recibe una palabra diferente',
  guessWord: 'Adivinar Palabra',
  createRoom: 'Crear Sala',
  joinRoom: 'Unirse a Sala',
  roomName: 'Nombre de la Sala',
  password: 'Contraseña (opcional)',
  maxPlayers: 'Máximo de Jugadores',
  botCount: 'Cantidad de Bots',
  create: 'Crear',
  createServer: 'Crear Servidor',
  createFirstServer: 'Crear el Primer Servidor',
  cancel: 'Cancelar',
  waitingForPlayers: 'Esperando jugadores...',
  gameStarting: 'El juego comenzará pronto',
  players: 'Jugadores',
  startGame: 'Iniciar Juego',
  leaveGame: 'Salir del Juego',
  youAreImpostor: '¡Eres el Impostor!',
  youAreCrewmate: 'Eres un Tripulante',
  impostorWord: 'Tu palabra secreta es:',
  crewmateWord: 'La palabra es:',
  discuss: 'Discutir',
  vote: 'Votar',
  skip: 'Saltar',
  voteFor: 'Votar por',
  noVote: 'No votar',
  votingResults: 'Resultados de la votación',
  wasVotedOut: 'fue expulsado',
  continue: 'Continuar',
  gameOver: 'Juego Terminado',
  crewmatesWin: '¡Los Tripulantes Ganaron!',
  impostorWins: '¡El Impostor Ganó!',
  hardMode: 'Modo Difícil',
  inviteFriends: 'Invitar Amigos',
  copyLink: 'Copiar Enlace',
  linkCopied: '¡Enlace copiado!',
  inviteMessage: 'Únete a mi partida de Impostor en UPG:',
  invitationCode: 'Código de Invitación',
  joinWithInvite: 'Unirse con Invitación',
  enterInviteCode: 'Ingresa el código de invitación',
  invalidInviteCode: 'Código de invitación inválido',
  inviteCopiedToClipboard: 'Invitación copiada al portapapeles',

  // Minecraft
  minecraftServer: 'Servidor Minecraft',
  copyIp: 'Copiar IP',
  copied: 'Copiado!',
  more: 'más',
  loadingServerStatus: 'Cargando estado del servidor...',
  stableSignal: '● Señal estable',
  onlinePlayers: 'Jugadores en Línea',
  serverOffline: 'Servidor fuera de línea',
  playersOnline: 'jugadores en línea',

  // General
  loading: 'Cargando...',
  error: 'Error',
  success: 'Éxito',
  close: 'Cerrar',
  open: 'Abrir',
  save: 'Guardar',
  delete: 'Eliminar',
  edit: 'Editar',
  confirm: 'Confirmar',
  yes: 'Sí',
  no: 'No',
  ok: 'Aceptar',
  back: 'Atrás',
  next: 'Siguiente',
  previous: 'Anterior',
  search: 'Buscar',
  filter: 'Filtrar',
  sort: 'Ordenar',
  settings: 'Configuración',
  help: 'Ayuda',
  about: 'Acerca de',
  contact: 'Contacto',
  terms: 'Términos',
  privacy: 'Privacidad',
  cookiesPolicy: 'Cookies',

  // Estados
  online: 'En línea',
  offline: 'Desconectado',
  connecting: 'Conectando...',
  connected: 'Conectado',
  disconnected: 'Desconectado',
  pending: 'Pendiente',
  completed: 'Completado',
  failed: 'Fallido',

  // Notificaciones
  messageSent: 'Mensaje enviado',
  messageFailed: 'Error al enviar mensaje',
  userJoined: 'se unió al chat',
  userLeft: 'salió del chat',
  userKicked: 'fue expulsado',
  userBanned: 'fue baneado',
  userSilenced: 'fue silenciado',
  colorChanged: 'cambió de color',
  trollActivated: 'activó modo troll',

  // Placeholders
  enterMessage: 'Escribe un mensaje...',
  enterUsername: 'Ingresa tu nombre de usuario',
  enterRoomName: 'Ingresa el nombre de la sala',
  enterPasswordPrompt: 'Ingresa la contraseña',

  // Errores
  networkError: 'Error de conexión',
  serverError: 'Error del servidor',
  invalidInput: 'Entrada inválida',
  roomNotFound: 'Sala no encontrada',
  roomFull: 'Sala llena',
  wrongPassword: 'Contraseña incorrecta',
  alreadyInGame: 'Ya estás en una partida',
  gameInProgress: 'Juego en progreso',
  notAuthorized: 'No autorizado',

  // Quiénes Somos
  whoWeAre: 'Quiénes Somos',
  aboutDescription: 'Somos una comunidad apasionada por los juegos...',
  ourMission: 'Nuestra Misión',
  missionDescription: 'Crear un espacio donde los gamers puedan...',
  ourTeam: 'Nuestro Equipo',
  teamDescription: 'Un grupo de entusiastas...',
  joinUs: 'Únete a Nosotros',
  joinDescription: 'Forma parte de nuestra comunidad...',

  // Hall of Fame
  hallOfFame: 'Salón de la Fama',
  topPlayers: 'Mejores Jugadores',
  rank: 'Rango',
  score: 'Puntuación',
  gamesPlayed: 'Partidas Jugadas',
  winRate: 'Tasa de Victoria',

  // UPG News
  upgNews: 'Noticias UPG',
  latestNews: 'Últimas Noticias',
  readMore: 'Leer Más',
  published: 'Publicado',
  author: 'Autor',

  // Voting
  voting: 'Votación',
  voteNow: 'Vota Ahora',
  results: 'Resultados',
  totalVotes: 'Votos Totales',
  winner: 'Ganador',

  // Who We Are
  ourStory: 'Nuestra Historia',
  storyDescription: 'UPG nació de la pasión por los juegos...',
  ourValues: 'Nuestros Valores',
  valuesDescription: 'Respeto, diversión, comunidad...',
  futurePlans: 'Planes Futuros',
  plansDescription: 'Estamos trabajando en nuevas características...',
};